added select time button/fixed game-img for large screens
Diegopie/Gaming-Calendar pull request #30
Opened 2020-09-02 22:35 UTC by volosevych

2020-09-03 19:53 UTC, Diegopie requested changes
This is looking good. There are a couple things that we could update so that it plays nicer with the QR generator. The biggest thing is that this was built on an old version of the master. While on this branch, use git merge master to sync with the current master branch and manage any conflicts that may appear.

2020-09-03 19:53 UTC, Diegopie commented on events.html
> +                                  <option>1</option>
Could these be updated to have a 0 in front of the single digit numbers? It will help with the QR code generator

2020-09-03 19:53 UTC, Diegopie commented on events.html
> +                              <input class="is-success minutes-input" type="number" placeholder="min" id="minutes" name="quantity" min="1" max="60">
We'll nee to change this to start at 0 and end at 59, could the single digit numbers also have a 0 in front of them?

2020-09-03 19:53 UTC, Diegopie commented on events.html
> +                        <div class="field">
Is it possible to center these time containers on the page so they match the other input boxes?

2020-09-04 01:06 UTC, slothings approved these changes

2020-09-04 01:06 UTC, Feizhi255 reviewed
looks good

2020-09-04 01:07 UTC, Diegopie approved these changes

2020-09-04 01:07 UTC, merged